name: 'olist_pipeline'
version: '1.0.0'
config-version: 2

profile: 'olist_pipeline'
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: external
      +options:
        format: parquet
